site_name: 'Open Sustainable Technology'
site_url: 'https://opensustain.tech/'
site_description: 'A directory and analysis of the open source ecosystem in the areas of climate change, sustainable energy, biodiversity and natural resources.'
repo_name: 'protontypes/open-sustainable-technology'
repo_url: 'https://github.com/protontypes/open-sustainable-technology'
base_url: 'https://opensustain.tech/'
edit_uri: ''
nav:
  - Projects: index.md
  - Spreadsheet: spreadsheet.md
  - Dashboard: dashboard.md  
  - Report: open-source-in-environmental-sustainability.md 
  - Education: education.md
  - Contribute: contributing.md
  - Blog:
      2023: 
        - "Connect Developers with Impactful Sustainability Projects" : blog/launch-climate-triage.md
        - "The Open Source Sustainability Ecosystem"  : blog/the-open-source-sustainability-ecosystem.md
      2022:
        - "You can preserve the Earth's livability with open source" : blog/you-can-preserve-the-earth-s-livability-with-open-source.md  
        - "Impact and potential of open source on climate technology": blog/impact-and-potential-of-open-source-on-climate-technology.md
        - "Openness as a key indicator for sustainable investment": blog/openness-as-a-key-indicator-for-sustainable-investment.md
      2021:
        - "Open Principles for a Sustainable Technology Transition": blog/open-principles-for-a-sustainable-technology_transition.md
      2020:
        - "Gathering Open Sustainable Technology": blog/gathering-open-sustainable-technology.md

theme:
  name: 'material'
  custom_dir: 'docs/overrides'
  logo: 'logo.png'
  favicon: 'favicon.png'
  palette:
        primary: 'teal'
        accent: 'light'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - search.highlight
    - search.suggest
    - navigation.top
    - navigation.tracking

    
extra_css:
    - css/extra.css

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: plotly
          class: mkdocs-plotly
          format: !!python/name:mkdocs_plotly_plugin.fences.fence_plotly
  - pymdownx.tabbed:
      alternate_style: true
  - meta
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - plotly

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/protontypes
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/protontypes
